### ISSUE TITLE
The name "Settings" does not exist in the current context

### ISSUE THREAD

**Issue by Servail** [Atlinx/Godot-Mono-CustomResourceRegistry#10]
Got this error after setting #nullables enable (there were some related errors on build, but that was an easy fix). Looks like the plugin script missing an entire Settings class! 
Tested in Godot v4.0 stable with godot-4.x branch.

**Comment by Atlinx** [comment]
Thanks for reporting that! Looks like I accidentally deleted the settings script whilst restructuring the repo.

**Comment by Atlinx** [comment]
Should by fixed by latest commit (I've also regenerated the v3.0.0 release to fix this issue as well). Please let me know if you still have any issues.
