### ISSUE TITLE
Cannot get plugin to load in 4.0.1 release.

### ISSUE THREAD

**Issue by tex111** [Atlinx/Godot-Mono-CustomResourceRegistry#12]
![ex1](https://user-images.githubusercontent.com/55551426/226882813-9d05247d-5002-45ac-baf3-e23c13c4c6c3.PNG)

**Comment by Atlinx** [comment]
Are there any errors that show up when building the c# solution? I'd be grateful if you could post them here.

**Comment by Atlinx** [comment]
I've tested this on this repo's demo project and everything worked. Does rebuilding the C# solution fix the error?

**Comment by tex111** [comment]
I tried on a fresh project with only the addon. Same error. No errors shown in console etc. If I had to guess there is some sort of dev package I am missing or perhaps I need to install VS2019 instead of just using rider. I will try installing both versions of .NET SDK and work from there.

**Comment by tex111** [comment]
Re-installing both versions of .NET did not fix it. Loading from the included project resulted in the same error. Deleting godot from App Data did not fix. I still think there is some sort of dependency issue here.

**Comment by Atlinx** [comment]
~~Are you downloading the addons folder from the main branch?~~ 

It works for me in a fresh project in 4.0.1
![image](https://user-images.githubusercontent.com/25368491/227242308-d98fa87d-4092-4faf-acee-fe0fc4ac9e05.png)

EDIT: Just tested the 3.0.0 release and it also works in a fresh 4.0.1 project for me.

**Comment by tex111** [comment]
I just did a fresh install of windows 10. Installed .NET SDK 7. Installed Godot 4.0.1 mono 64 bit. Downloaded the latest release from this repo. Loaded a fresh project and made a c# script and built the solution. Added the plugin. Rebuild solution. Go to plugin menu and attempt to enable. I am still getting the error. There is a missing dependency here.

**Comment by Atlinx** [comment]
What does your csproj file say? Also, to clarify, are there no errors when building right? This plugin is self-contained, depending on only Godot and System so there's not much that can go wrong. Also [godot currently uses NET 6](https://godotengine.org/article/whats-new-in-csharp-for-godot-4-0/#:~:text=The%20Godot%20API%20is%20also,NET%20LTS%20release.), so using .NET 7 may cause some issues.

**Comment by tex111** [comment]
```
<Project Sdk="Godot.NET.Sdk/4.0.1">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <EnableDynamicLoading>true</EnableDynamicLoading>
    <RootNamespace>AetherAeon</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <Folder Include="Scripts\Class" />
    <Folder Include="Scripts\Database" />
    <Folder Include="Scripts\Node" />
    <Folder Include="Scripts\Resource" />
  </ItemGroup>
</Project>
```

Correct. No errors when building.

**Comment by Atlinx** [comment]
Do any of these workarounds work for you? https://github.com/godotengine/godot/issues/39921. You can also try removing the `<ItemGroup>` tag, since maybe it's excluding the addons folder. 

Here's the csproj of the empty project I made
```xml
<Project Sdk="Godot.NET.Sdk/4.0.1">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <EnableDynamicLoading>true</EnableDynamicLoading>
  </PropertyGroup>
</Project>
```

**Comment by tex111** [comment]
I checked out the link and tried the fixes suggested. No dice. I tried making a new empty plugin and had the same issue with loading so this isn't an issue with this plugin it is a godot issue, Thanks for all the help.
