### ISSUE TITLE
Refresh custom types on solution build.

### ISSUE THREAD

**Issue by matte250** [Atlinx/Godot-Mono-CustomResourceRegistry#16]
I thought that building the project would be enough to register any custom types. But then I found a comment in the code for the plugin that said that there was no way to automate this.

You can actually implement the [ISerializationListener ](https://github.com/godotengine/godot/blob/2f73a059cefadcd944b6874f2557ec82e46a562d/modules/mono/glue/GodotSharp/GodotSharp/Core/Interfaces/ISerializationListener.cs#L19) to get the behavior you are probably after. It runs whenever assemblies are reloaded with the added benefit of running only if the assembly has changed.

I created a branch and PR for you [here](https://github.com/Atlinx/Godot-Mono-CustomResourceRegistry/pull/15) as I cant link the issue.

**Comment by Atlinx** [comment]
Closed by #15
