### ISSUE TITLE
There is no ICustomNode interface

### ISSUE THREAD

**Issue by TandersT** [Atlinx/Godot-Mono-CustomResourceRegistry#2]
Followed the guide, and Godot.Resource seems to work fine, I got the CRR tab and everything. But the interface does not seem to exists?

Anything looks out of the ordinary here?

[screenshot of setup](https://imgur.com/a/mYBGaZW)

**Comment by Atlinx** [comment]
My bad -- I had the interface renamed to `ICustomNodeType` and forgot to update the `README.md`. My latest commits have renamed the interface back to `ICustomNode`. If you download this repo again and reinstall the plugin you should be good to go.

After reinstalling the plugin, you may also have to import the namespace of the plugin by adding `using  MonoCustomResourceRegistry` to the top of your C# class whenever you want to implement `ICustomNode`.

**Comment by Atlinx** [comment]
@TandersT if my new commits fixed the interface problem for you, make sure to close this issue.

**Comment by TandersT** [comment]
I can access the interface now with the new commit. Thanks!
