### ISSUE TITLE
No licence

### ISSUE THREAD

**Issue by kanroot** [Atlinx/Godot-Mono-CustomResourceRegistry#6]
Hi,  this plugin don't have a license and I don't know if this work is a fork of CustomResourceRegisterPlugin made by wmigor or only based in his idea.

Would you mind adding a licence file?

**Comment by Atlinx** [comment]
This is technically an unofficial fork of wmigor's repository, so I'll ask them for permission to add a license.

**Comment by wmigor** [comment]
i added mit license in my repo

**Comment by Atlinx** [comment]
I have copied over wmigor's license. 👍
